### PR TITLE
apiTS changed to long

### PR DESCRIPTION
**Pull request by karthikbr82**
https://www.pivotaltracker.com/story/show/116871765

### CODE REVIEW

**Comment by karthikbr82** [comment]
@satucallstats, can you please check if this change affects dashboard for bridge in anyway.

**Comment by marcinag** [comment]
LGTM

**Comment by satucallstats** [comment]
Should be good by looking at the code. There's a parseInt call for the apiTS, which becomes unnecessary but it causes no problems if you give it a number instead of a string.

**Comment by satucallstats** [comment]
Is there a way it can be tested before it goes live?

**Pull request merged**
